apiVersion: v2
annotations:
  category: Frontend
name: debuger
description: SVTECH Debuger
engine: gotpl

dependencies:
  - name: common
    repository: https://moophat.github.io/SVTECH_Public_Helmchart/artifacthub/
    tags:
      - bitnami-common
    version: 1.x.x

version: 1.0.0
appVersion: "v1.0.0"
