{{- if and (not .Values.auth.existingSecret) (not .Values.auth.existingSecretPerPassword) }}
{{- $secretName := include "common.names.fullname" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }} 
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: freeradius
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  db-database: {{ ternary (randAlphaNum 10) .Values.externalDatabase.database (empty .Values.externalDatabase.database) | b64enc | quote }}
  db-user: {{ ternary (randAlphaNum 10) .Values.externalDatabase.user (empty .Values.externalDatabase.user) | b64enc | quote }}
  db-password: {{ ternary (randAlphaNum 20) .Values.externalDatabase.password (empty .Values.externalDatabase.password) | b64enc | quote }}
  {{- if (.Values.sitesEnabled.status.enabled) }}
  sites-status-secret: {{ include "common.secrets.passwords.manage" (dict "secret" $secretName "key" "sites-status-secret" "length" 10 "providedValues" (list "sitesEnabled.status.secret") "context" $) }}
  {{- end }}
{{- end }}
